<?php


class MyException extends Exception
{

    public function __construct($message, $code = 0)
    {
        parent::__construct($message, $code);
    }

    function __toString()
    {
//        echo $this->message;
//        parent::__toString(); // TODO: Change the autogenerated stub
//        return 'aaa';
        return __CLASS__ . ": [{$this->code}]: {$this->message}\n";
//        return $this->message;
    }
//


//    final public function getMessage()
//    {
//
//    }

}


function throwErr($msg)
{
    throw new MyException($msg);
}


try {
    throwErr('12312');
} catch (MyException $e) {
    echo $e->getMessage();
}



